import type { Category, Difficulty } from "./types";

export interface SeedEntry {
  name: string;
  category: Category;
  tags: string[];
  cookTime: number;
  difficulty: Difficulty;
}

type Row = [string, string[], number, Difficulty];

const BREAKFAST: Row[] = [
  ["Idli", ["VEG", "HEALTHY"], 30, "medium"],
  ["Dosa", ["VEG"], 30, "medium"],
  ["Poha", ["VEG", "QUICK"], 15, "easy"],
  ["Handvo", ["VEG", "HEALTHY"], 60, "hard"],
  ["Rava Uttapam", ["VEG"], 25, "easy"],
  ["Bread Upma", ["VEG", "QUICK"], 15, "easy"],
  ["Semiya Upma", ["VEG", "QUICK"], 20, "easy"],
  ["Khara Bath", ["VEG"], 25, "easy"],
  ["Moong Dal Dosa", ["VEG", "HEALTHY"], 30, "medium"],
  ["Oats Chilla", ["VEG", "HEALTHY", "QUICK"], 15, "easy"],
  ["Upma", ["VEG", "QUICK"], 20, "easy"],
  ["Masala Dosa", ["VEG"], 45, "hard"],
  ["Adai Dosa", ["VEG", "HEALTHY"], 30, "medium"],
  ["Rava Idli", ["VEG"], 30, "medium"],
  ["Mooli Paratha", ["VEG"], 35, "medium"],
  ["Gobi Paratha", ["VEG"], 35, "medium"],
  ["Moong Dal Chilla", ["VEG", "HEALTHY", "QUICK"], 20, "easy"],
  ["Besan Chilla", ["VEG", "QUICK"], 15, "easy"],
  ["Aloo Paratha", ["VEG"], 35, "medium"],
  ["Medu Vada", ["VEG"], 40, "hard"],
  ["Poori", ["VEG"], 30, "medium"],
  ["Brown Rice Dosa", ["VEG", "HEALTHY"], 30, "medium"],
  ["Wheat Dosa", ["VEG", "HEALTHY"], 20, "easy"],
  ["Bhatura", ["VEG"], 30, "medium"],
  ["Sabudana Khichdi", ["VEG"], 30, "medium"],
  ["Oats Dosa", ["VEG", "HEALTHY", "QUICK"], 20, "easy"],
  ["Idli Sambar", ["VEG", "HEALTHY"], 40, "medium"],
  ["Mixed Dal Dosa", ["VEG", "HEALTHY"], 30, "medium"],
  ["Pesarattu", ["VEG", "HEALTHY"], 30, "medium"],
  ["Oats Upma", ["VEG", "HEALTHY", "QUICK"], 20, "easy"],
  ["Paniyaram", ["VEG"], 30, "medium"],
  ["Thepla", ["VEG", "HEALTHY"], 30, "medium"],
  ["Rava Dosa", ["VEG", "QUICK"], 20, "easy"],
  ["Rava Kesari", ["VEG"], 25, "easy"],
  ["Cheese Dosa", ["VEG"], 30, "medium"],
  ["Neer Dosa", ["VEG"], 25, "easy"],
  ["Akki Roti", ["VEG", "HEALTHY"], 30, "medium"],
  ["Oats Idli", ["VEG", "HEALTHY"], 30, "medium"],
  ["Palak Paratha", ["VEG", "HEALTHY"], 35, "medium"],
  ["Methi Paratha", ["VEG", "HEALTHY"], 35, "medium"],
  ["Set Dosa", ["VEG"], 30, "medium"],
  ["Millet Dosa", ["VEG", "HEALTHY"], 25, "medium"],
  ["Appe", ["VEG"], 25, "medium"],
  ["Tomato Upma", ["VEG", "QUICK"], 20, "easy"],
  ["Aval Upma", ["VEG", "QUICK"], 15, "easy"],
  ["Ragi Dosa", ["VEG", "HEALTHY"], 25, "medium"],
  ["Bread Pakora", ["VEG", "QUICK"], 20, "easy"],
  ["Idli Upma", ["VEG", "QUICK"], 15, "easy"],
  ["Ragi Roti", ["VEG", "HEALTHY"], 30, "medium"],
  ["Podi Idli", ["VEG", "QUICK"], 15, "easy"],
  ["Punugulu", ["VEG"], 30, "medium"],
  ["Ragi Idli", ["VEG", "HEALTHY"], 35, "medium"],
  ["Dalia", ["VEG", "HEALTHY", "QUICK"], 20, "easy"],
  ["Savory French Toast", ["VEG", "QUICK"], 15, "easy"],
  ["Mix Veg Paratha", ["VEG", "HEALTHY"], 35, "medium"],
  ["Kothu Parotta", ["VEG"], 30, "medium"],
  ["Samosa", ["VEG"], 60, "hard"],
  ["Sandwich (Bombay)", ["VEG", "QUICK"], 15, "easy"],
];

const LUNCH_DINNER_BASE: Row[] = [
  ["Cauliflower Curry", ["VEG", "HEALTHY"], 35, "medium"],
  ["Mango Curry", ["VEG"], 30, "medium"],
  ["Red Lentil Curry", ["VEG", "HEALTHY", "QUICK"], 25, "easy"],
  ["Aloo Chana", ["VEG", "HEALTHY"], 35, "medium"],
  ["Chayote Sabzi", ["VEG", "HEALTHY", "QUICK"], 20, "easy"],
  ["Chickpea Curry", ["VEG", "HEALTHY"], 35, "medium"],
  ["Gobi Masala", ["VEG"], 30, "medium"],
  ["Butternut Squash Curry", ["VEG", "HEALTHY"], 35, "medium"],
  ["Baingan Bharta", ["VEG", "HEALTHY"], 40, "medium"],
  ["Saag Aloo", ["VEG", "HEALTHY"], 30, "medium"],
  ["Chana Masala", ["VEG", "HEALTHY"], 35, "medium"],
  ["Tofu Curry", ["VEG", "HEALTHY"], 30, "medium"],
  ["Mirchi Ka Salan", ["VEG"], 35, "medium"],
  ["Bagara Baingan", ["VEG"], 40, "medium"],
  ["Aloo Gobi", ["VEG", "QUICK"], 25, "easy"],
  ["Brinjal Curry", ["VEG"], 30, "medium"],
  ["Beetroot Sabzi", ["VEG", "HEALTHY"], 25, "easy"],
  ["Aloo Mushroom Curry", ["VEG"], 30, "medium"],
  ["Cabbage Curry", ["VEG", "HEALTHY", "QUICK"], 20, "easy"],
  ["Chana Saag", ["VEG", "HEALTHY"], 35, "medium"],
  ["Cabbage Kootu", ["VEG", "HEALTHY"], 30, "medium"],
  ["Beans Curry", ["VEG", "HEALTHY"], 30, "medium"],
  ["Eggplant Potato Curry", ["VEG"], 30, "medium"],
  ["Ridge Gourd Dal", ["VEG", "HEALTHY"], 30, "medium"],
  ["Bhindi Pulusu", ["VEG"], 30, "medium"],
  ["Bottle Gourd Curry", ["VEG", "HEALTHY", "QUICK"], 25, "easy"],
  ["Tindora Curry", ["VEG", "QUICK"], 25, "easy"],
  ["Drumstick Curry", ["VEG", "HEALTHY"], 35, "medium"],
  ["Palak Curry", ["VEG", "HEALTHY", "QUICK"], 25, "easy"],
  ["Aloo Kurma", ["VEG"], 35, "medium"],
  ["Jackfruit Seeds Curry", ["VEG"], 40, "medium"],
  ["Paneer Makhani", ["VEG"], 40, "medium"],
  ["Karela Sabzi", ["VEG", "HEALTHY"], 25, "easy"],
  ["Raw Banana Fry", ["VEG", "QUICK"], 20, "easy"],
  ["Sweet Potato Stir Fry", ["VEG", "HEALTHY", "QUICK"], 20, "easy"],
  ["Stuffed Brinjal Fry", ["VEG"], 35, "medium"],
  ["Aloo Methi", ["VEG", "QUICK"], 20, "easy"],
  ["Beetroot Thoran", ["VEG", "HEALTHY", "QUICK"], 20, "easy"],
  ["Bhindi Fry", ["VEG", "QUICK"], 20, "easy"],
  ["Cabbage Sabzi", ["VEG", "HEALTHY", "QUICK"], 15, "easy"],
  ["Broccoli Stir Fry", ["VEG", "HEALTHY", "QUICK"], 15, "easy"],
  ["Baby Corn Fry", ["VEG", "QUICK"], 20, "easy"],
  ["Beans Poriyal", ["VEG", "HEALTHY", "QUICK"], 20, "easy"],
  ["Ridge Gourd Fry", ["VEG", "HEALTHY", "QUICK"], 20, "easy"],
  ["Bottle Gourd Sabzi", ["VEG", "HEALTHY", "QUICK"], 20, "easy"],
  ["Tindora Fry", ["VEG", "QUICK"], 20, "easy"],
  ["Yam Fry", ["VEG"], 25, "easy"],
  ["Brinjal Fry", ["VEG", "QUICK"], 20, "easy"],
  ["Bhindi Do Pyaza", ["VEG", "QUICK"], 20, "easy"],
  ["Zucchini Stir Fry", ["VEG", "HEALTHY", "QUICK"], 15, "easy"],
  ["Moringa Sabzi", ["VEG", "HEALTHY"], 25, "easy"],
  ["Dry Chana", ["VEG", "HEALTHY"], 30, "medium"],
  ["Radish Stir Fry", ["VEG", "HEALTHY", "QUICK"], 20, "easy"],
  ["Mushroom Fry", ["VEG", "QUICK"], 20, "easy"],
  ["Aloo Masala", ["VEG", "QUICK"], 20, "easy"],
  ["Aloo Fry", ["VEG", "QUICK"], 20, "easy"],
];

const DALS: Row[] = [
  ["Dal Tadka", ["VEG", "HEALTHY"], 30, "easy"],
  ["Dal Fry", ["VEG", "HEALTHY"], 30, "easy"],
  ["Dal Makhani", ["VEG"], 60, "hard"],
  ["Masoor Dal", ["VEG", "HEALTHY", "QUICK"], 25, "easy"],
  ["Toor Dal", ["VEG", "HEALTHY"], 30, "easy"],
  ["Chana Dal", ["VEG", "HEALTHY"], 35, "medium"],
  ["Moong Dal", ["VEG", "HEALTHY", "QUICK"], 20, "easy"],
  ["Dal Palak", ["VEG", "HEALTHY"], 30, "easy"],
  ["Methi Dal", ["VEG", "HEALTHY"], 30, "easy"],
  ["Green Moong Dal", ["VEG", "HEALTHY", "QUICK"], 25, "easy"],
  ["Sambar", ["VEG", "HEALTHY"], 35, "medium"],
  ["Tomato Dal", ["VEG", "HEALTHY", "QUICK"], 25, "easy"],
  ["Mango Dal", ["VEG"], 30, "medium"],
  ["Rajma", ["VEG", "HEALTHY"], 50, "medium"],
  ["Chole", ["VEG"], 45, "medium"],
  ["Khichdi", ["VEG", "HEALTHY", "QUICK"], 25, "easy"],
  ["Pumpkin Dal", ["VEG", "HEALTHY"], 30, "easy"],
  ["Kadala Curry", ["VEG", "HEALTHY"], 40, "medium"],
  ["Gongura Dal", ["VEG"], 30, "medium"],
  ["Palak Dal", ["VEG", "HEALTHY"], 30, "easy"],
];

const PANEER: Row[] = [
  ["Palak Paneer", ["VEG", "HEALTHY"], 35, "medium"],
  ["Paneer Butter Masala", ["VEG"], 40, "medium"],
  ["Kadai Paneer", ["VEG"], 35, "medium"],
  ["Paneer Tikka Masala", ["VEG"], 40, "medium"],
  ["Saag Paneer", ["VEG", "HEALTHY"], 35, "medium"],
  ["Paneer Jalfrezi", ["VEG", "QUICK"], 25, "easy"],
  ["Malai Kofta", ["VEG"], 50, "hard"],
  ["Paneer Curry", ["VEG"], 35, "medium"],
  ["Paneer Pasanda", ["VEG"], 40, "medium"],
];

const RICE: Row[] = [
  ["Veg Fried Rice", ["VEG", "QUICK"], 25, "easy"],
  ["Tomato Rice", ["VEG", "QUICK"], 20, "easy"],
  ["Coconut Rice", ["VEG", "QUICK"], 20, "easy"],
  ["Veg Biryani", ["VEG"], 60, "hard"],
  ["Aloo Baingan Rice", ["VEG"], 30, "medium"],
];

const MORE_CURRIES: Row[] = [
  ["Vegetable Jalfrezi", ["VEG", "HEALTHY", "QUICK"], 25, "easy"],
  ["Vegetable Curry", ["VEG", "HEALTHY"], 30, "medium"],
  ["Kadhi Pakora", ["VEG"], 40, "medium"],
  ["Aloo Matar", ["VEG", "QUICK"], 25, "easy"],
  ["Aloo Baingan", ["VEG", "QUICK"], 25, "easy"],
  ["Bombay Aloo", ["VEG", "QUICK"], 20, "easy"],
  ["Butter Chickpeas", ["VEG"], 35, "medium"],
  ["Spicy Garlic Mushrooms", ["VEG", "QUICK"], 15, "easy"],
];

const DINNER_ONLY: Row[] = [
  ["Chapati", ["VEG", "QUICK"], 20, "easy"],
  ["Butter Naan", ["VEG"], 35, "medium"],
  ["Kulcha", ["VEG"], 30, "medium"],
  ["Tandoori Roti", ["VEG", "QUICK"], 20, "easy"],
  ["Paneer Paratha", ["VEG"], 35, "medium"],
  ["Lauki Paratha", ["VEG", "HEALTHY"], 30, "medium"],
  ["Multigrain Roti", ["VEG", "HEALTHY"], 20, "easy"],
  ["Puran Poli", ["VEG"], 60, "hard"],
  ["Veg Wrap", ["VEG", "QUICK"], 20, "easy"],
  ["Beetroot Paratha", ["VEG", "HEALTHY"], 30, "medium"],
];

const SNACKS: Row[] = [
  ["Onion Pakoda", ["VEG"], 20, "easy"],
  ["Veg Puff", ["VEG"], 45, "hard"],
  ["Gobi 65", ["VEG", "QUICK"], 25, "easy"],
  ["Dabeli", ["VEG"], 30, "medium"],
  ["Kachori", ["VEG"], 50, "hard"],
  ["Makhana Snack", ["VEG", "HEALTHY", "QUICK"], 10, "easy"],
  ["Mirchi Bajji", ["VEG"], 25, "easy"],
  ["Veg Cutlet", ["VEG"], 30, "medium"],
  ["Aloo Tikki", ["VEG"], 30, "medium"],
  ["Khaman Dhokla", ["VEG", "HEALTHY"], 30, "medium"],
  ["Batata Vada", ["VEG"], 30, "medium"],
  ["Hara Bhara Kabab", ["VEG", "HEALTHY"], 30, "medium"],
  ["Paneer Tikka", ["VEG"], 30, "medium"],
  ["Pav Bhaji", ["VEG"], 40, "medium"],
  ["Samosa", ["VEG"], 60, "hard"],
  ["Aloo Chaat", ["VEG", "QUICK"], 20, "easy"],
  ["Sabudana Vada", ["VEG"], 30, "medium"],
  ["Bhel Puri", ["VEG", "QUICK"], 10, "easy"],
  ["Paneer Pakora", ["VEG"], 20, "easy"],
  ["Masala Vada", ["VEG"], 30, "medium"],
  ["Veg Grilled Sandwich", ["VEG", "QUICK"], 15, "easy"],
  ["Rava Vada", ["VEG"], 25, "easy"],
  ["Vegetable Pakora", ["VEG"], 20, "easy"],
  ["Tikki Chaat", ["VEG"], 30, "medium"],
  ["Chilli Paneer", ["VEG"], 25, "easy"],
  ["Gobi Manchurian", ["VEG"], 35, "medium"],
  ["Misal Pav", ["VEG"], 40, "medium"],
  ["Corn Cutlet", ["VEG", "HEALTHY"], 25, "easy"],
  ["Palak Pakoda", ["VEG", "QUICK"], 15, "easy"],
  ["Spring Rolls", ["VEG"], 40, "medium"],
  ["Bread Masala", ["VEG", "QUICK"], 15, "easy"],
  ["Mysore Bonda", ["VEG"], 25, "medium"],
  ["Chai", ["VEG", "QUICK"], 5, "easy"],
];

function toEntries(rows: Row[], category: Category): SeedEntry[] {
  return rows.map(([name, tags, cookTime, difficulty]) => ({
    name, category, tags, cookTime, difficulty,
  }));
}

function bothCategories(rows: Row[]): SeedEntry[] {
  return [
    ...toEntries(rows, "LUNCH"),
    ...toEntries(rows, "DINNER"),
  ];
}

export const SEED_MEALS: SeedEntry[] = [
  ...toEntries(BREAKFAST, "BREAKFAST"),
  ...toEntries(LUNCH_DINNER_BASE, "LUNCH"),
  ...toEntries(LUNCH_DINNER_BASE, "DINNER"),
  ...bothCategories(DALS),
  ...bothCategories(PANEER),
  ...bothCategories(RICE),
  ...bothCategories(MORE_CURRIES),
  ...toEntries(DINNER_ONLY, "DINNER"),
  ...toEntries(SNACKS, "SNACK"),
];
